# Generated by Django 2.0.1 on 2018-01-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'permissions': (('view_recipe', 'View recipe'),)},
        ),
    ]
