# Generated by Django 2.0.1 on 2018-01-07 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_auto_20180107_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='modification_date',
            field=models.DateField(auto_now=True),
        ),
    ]
