# Generated by Django 2.0.1 on 2018-01-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20180108_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='modification_date',
            new_name='modified',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
