# Generated by Django 2.0.1 on 2018-01-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_auto_20180108_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
